### ISSUE TITLE
Better make backup somewhere for precaution

### ISSUE THREAD

**Issue by dtantono** [Logboy2000/yuzu-archive#1]
it seems Nintendo hate this app and this site is not safe anymore. I suggest you hosted is somewhere as a backup

https://kotaku.com/nintendo-switch-yuzu-emulator-github-piracy-zelda-1851452740

**Comment by Logboy2000** [comment]
You should check out [Suyu](https://suyu.dev/), it's based on yuzu and is being currently developed for all platforms. Better than sticking to an old version of yuzu.
